export default function handler(req, res) {
    const data = [
        {
          "date": "6/13/2024",
          "owner": "THERESA MARIE VIDAL",
          "pet_name": "NOAH",
          "location": "LABOGON",
          "contact": "9452662596",
          "species": "DOG",
          "breed": "MIXED",
          "sex": "M",
          "weight": "14 KG",
          "color": "CHOCO BROWN",
          "age": "10 MOS",
          "vet": "DEFENSOR 689788",
          "microchip": "900215010414027"
        },
        {
          "date": "6/13/2024",
          "owner": "ROLAND PESCADERO",
          "pet_name": "SCARLET",
          "location": "MANTUYONG",
          "contact": "9352372230",
          "species": "DOG",
          "breed": "MIXED",
          "sex": "F",
          "birth_date": "6/24/2017",
          "color": "BROWN",
          "age": "7 YRS",
          "vet": "DEFENSOR 689788",
          "microchip": "900215010414021"
        },
        {
          "date": "6/20/2024",
          "owner": "FELIX ESCONDE",
          "pet_name": "CHOKI",
          "location": "CANUMAY, LABOGON",
          "contact": "9311174329",
          "species": "DOG",
          "breed": "MIXED",
          "sex": "M",
          "weight": "20 KG",
          "color": "BROWN/WHITE",
          "age": "2 YRS",
          "vet": "DEFENSOR 689788",
          "microchip": "900215010414028"
        },
        {
          "date": "6/20/2024",
          "owner": "RONALYN SUNGAHID",
          "pet_name": "KING",
          "location": "RIVERSIDE, LOOC",
          "contact": "9338169200",
          "species": "DOG",
          "breed": "ASPIN",
          "sex": "M",
          "color": "WHITE/BROWN",
          "vet": "DEFENSOR 689788",
          "microchip": "900215010414023"
        },
        {
          "date": "8/2/2024",
          "owner": "LEGAL OFFICE",
          "pet_name": "AMICUS",
          "location": "DA RFO 7",
          "contact": "9559240800",
          "species": "CAT",
          "breed": "MIXED",
          "sex": "M",
          "birth_date": "7/19/2021",
          "color": "WHITE",
          "age": "4 YRS",
          "vet": "DEFENSOR 689788",
          "microchip": "900215010415461"
        },
        {
          "date": "8/2/2024",
          "owner": "XEMENIA C. JUDAYA",
          "pet_name": "MANDA",
          "location": "DA RFO 7",
          "contact": "9176193835",
          "species": "DOG",
          "breed": "MIXED",
          "sex": "F",
          "weight": "88 KG",
          "color": "BROWN",
          "age": "3 YRS",
          "microchip": "900215010414030"
        },
        {
          "date": "8/8/2024",
          "owner": "CARMEN LABORTE",
          "pet_name": "PAAKI TANGKOG",
          "location": "SUBANGDAKU",
          "contact": "9610664967",
          "species": "DOG",
          "breed": "ASPIN",
          "sex": "M",
          "birth_date": "7/12/2022",
          "color": "BLACK",
          "age": "7 MOS",
          "email": "patrickswenatillo@gmail.com",
          "microchip": "900215010415464"
        },
        {
          "date": "8/8/2024",
          "owner": "DULCESIMA ELECCION",
          "pet_name": "TONTON",
          "location": "SUBANGDAKU",
          "contact": "9665203019",
          "species": "DOG",
          "breed": "ASPIN",
          "sex": "M",
          "birth_date": "1/4/2024",
          "color": "BLACK/WHITE",
          "age": "4 MOS",
          "email": "abella@gmail.com",
          "microchip": "900215010415400"
        },
        {
          "date": "9/17/2024",
          "owner": "JOSEPH FLORES",
          "pet_name": "PARKER",
          "location": "LOOC",
          "contact": "9454333850",
          "species": "CAT",
          "breed": "PUSPIN",
          "sex": "M",
          "birth_date": "11/20/2004",
          "color": "WHITE/BLACK",
          "age": "1 YR",
          "email": "binitkilds1973@gmail.com",
          "microchip": "900215010413346"
        },
        {
          "date": "9/20/2024",
          "owner": "VENER SANCHEZ",
          "pet_name": "LEXIE",
          "location": "OPAO",
          "contact": "9433935568",
          "species": "DOG",
          "breed": "MIXED",
          "sex": "F",
          "color": "CREME",
          "age": "1.3 YR",
          "microchip": "900215010413950"
        }
      ]
      
    res.status(200).json(data);
  }
  